In [47]:
import numpy as np

import pandas as pd

In [48]:
!cat examples/ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [49]:
df = pd.read_csv("examples/ex1.csv")

df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

#### Files without header row

In [50]:
!cat examples/ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [51]:
df = pd.read_csv("examples/ex2.csv", header=None)

df

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

#### Adding a header manually

In [52]:
df = pd.read_csv("examples/ex2.csv", names=["one", "two", "three", "four","five", "six"])

df

   one  two  three  four   five  six
0    1    2      3     4  hello  NaN
1    5    6      7     8  world  NaN
2    9   10     11    12    foo  NaN

Suppose you wanted the
column to be the index of the returned DataFrame.
message
You can either indicate you want the column at index 4 or named
using
"message"
the
argument:
index_col

In [53]:
df = pd.read_csv("examples/ex1.csv" , index_col="message")

df

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [54]:
names = ["a","b","c","d","message"]
df = pd.read_csv("examples/ex1.csv" ,names = names, index_col="message")
df

         a   b   c   d
message
message  a   b   c   d
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

#### Hierarchial Index

In [55]:
!cat examples/csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [56]:
parsed = pd.read_csv("examples/csv_mindex.csv", index_col=["key1","key2"])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In some cases, a table might not have a fixed delimiter, using whitespace or some
other pattern to separate fields.

In [57]:
!cat examples/ex3.txt

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

the fields here are separated by a
variable amount of whitespace. In these cases, you can pass a regular expression as a
delimiter for
csv. This can be expressed by the regular expression \s+,
pandas.read_
\
so we have then

In [58]:
result = pd.read_csv("examples/ex3.txt", sep="\s+")
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

Because there was one fewer column name than the number of data rows,
infers that the first column should be the DataFrame’s index in
pandas.read_csv
this special case.

In some cases, you may need to read in a file that has a header row, but the first
few rows are actually data. You can skip the header row(s) by passing the number of
rows to skip as the header parameter:

In [59]:
!cat examples/ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [60]:
pd.read_csv("examples/ex4.csv", skiprows=[0,2,3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

#### Handling Missing Data while reading

Missing data is usually either not present (empty string) or marked by some sentinel (placeholder) value. By default, pandas uses a set of commonly
occurring sentinels, such as
 NULL
 and NA

In [61]:
!cat examples/ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [62]:
result = pd.read_csv("examples/ex5.csv")
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [63]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

The
option accepts a sequence of strings to add to the default list of strings
na_values
recognized as missing:

In [64]:
result = pd.read_csv("examples/ex5.csv", na_values=["NULL"])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

pandas.read_csv has a list of many default NA value representations, but these
pandas.read_csv
defaults can be disabled with the
option:
keep_default_na

In [65]:
result2 = pd.read_csv("examples/ex5.csv", keep_default_na=False)
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [66]:
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [67]:
result3 = pd.read_csv("examples/ex5.csv", keep_default_na=False, na_values=["NA"])
result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [68]:
result3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

Different NA sentinels can be specified for each column in a dictionary:

In [69]:
sentinels = {"message": ["foo", "NA"], "something": ["two"]}
pd.read_csv("examples/ex5.csv", na_values=sentinels, keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

#### Reading text Files in Pieces

When processing very large files or figuring out the right set of arguments to cor
rectly
process a large file, you may want to read only a small piece of a file or iterate
through smaller chunks of the file.

In [70]:
# Make pandas display settings more compact 

pd.options.display.max_rows = 10

In [71]:
!cat examples/ex6.csv

one,two,three,four,key
0.467976300189,-0.0386485396255,-0.295344251987,-1.82472622729,L
-0.358893469543,1.40445260007,0.704964644926,-0.200638304015,B
-0.50184039929,0.659253707223,-0.421690619312,-0.0576883018364,G
0.204886212202,1.07413396504,1.38836131252,-0.982404023494,R
0.354627914484,-0.133115852296,0.283762637978,-0.837062961653,Q
1.81748001608,0.742272722638,0.419394843928,-2.25103520513,Q
-0.776764319165,0.935517747061,-0.332871759623,-1.87564085416,U
-0.913134961617,1.53062351168,-0.572656719239,0.477252252981,K
0.358479538224,-0.49757199147,-0.367016188009,0.507701778685,S
-1.74087710829,-1.16041658062,-1.63783027929,2.17220101238,G
0.24056373835,-0.328249185208,1.25215525783,1.07279626643,8
0.764018252198,1.16547617218,-0.639544262638,1.49525751956,R
0.571034923177,-0.310537224251,0.582437274651,-0.2987651796,1
2.31765810894,0.430709506296,-1.33421573445,0.199679483557,P
1.54777073472,-1.11975292512,-2.27763354506,0.329585909852,J
-1.31060811665,0.401719086645,-1.00098707369,1.15670834954,E
-0.0884964396951,0.634711729043,0.153323985774,0.415334751149,B
-0.0186628260149,-0.247487241047,-1.44652215689,0.750937748749,A
-0.0701272145463,-1.57909726069,0.120891794918,0.671431885035,F
-0.194677940725,-0.492039150308,2.35960484963,0.319810396195,H
-0.248617847177,0.868706587235,-0.492226143765,-0.717959381922,W
-1.09154895394,-0.867110226119,-0.647760443099,-0.832561559975,C
0.641404300148,-0.138821578977,-0.621962804042,-0.284839425379,C
1.21640846838,0.99268666512,0.165161778012,-0.0696186082242,V
-0.564474180519,0.792832268133,0.747052842907,0.57167515791,I
1.75987899507,-0.515665834496,-0.230480686323,1.36231722352,S
0.126266090531,0.309281375664,0.38281996138,-0.239199054993,L
1.33436047951,-0.100152166835,-0.840730552173,-0.643966598255,6
-0.737620017711,0.278087463151,-0.053235240431,-0.950971590734,J
-1.1484864849,-0.986292150868,-0.144963115417,0.124362404338,Y
1.63059449241,0.243886206002,0.468368306354,1.25804787443,F
1.04488953219,0.0807175385621,0.857885542829,-0.298381802517,J
-0.262542542362,-1.61519874791,-1.08723871374,0.759029075237,T
0.0201440713103,1.10779156618,-0.559435335039,-0.481925210095,M
-1.20391554609,1.88534310731,-0.0804704068388,0.25064589327,J
0.366914548813,-2.43008643092,-1.05344696342,0.346278884194,A
0.434220473424,-0.0798625386706,-0.422976747932,-0.0742721760915,I
0.0406656980213,-1.81021570262,-0.189192727269,1.22926636581,G
1.33845943246,0.338489099729,-0.213446105129,2.32592341971,Q
0.572981073363,0.782663875351,1.30767321124,1.61995725335,X
0.762428447112,-0.648528798886,1.93651473707,-1.15966561312,J
-1.25204557796,-1.53853949038,1.0422813822,0.623835121823,A
-0.0475302140596,-0.494310199706,-0.165460018905,0.472929032513,J
0.124547711991,0.730791450242,-0.25752685093,-1.51125664924,G
0.801889237656,-0.462780621429,-1.73462083332,0.674768319362,R
-0.992306666472,-1.09683007882,-2.0617943017,0.035390605957,R
-0.109662774864,2.57709376617,0.91356252242,0.613594050216,V
-0.541680906279,1.5100313553,0.467944825377,0.553225037837,N
-0.0795865737601,-0.609923697841,0.35383422895,1.10803005914,M
-0.0437516462601,-0.410666385961,-0.729599036366,0.263223371713,P
-0.761490177447,1.10418191625,1.27060866366,-0.319284452382,O
-0.804975073037,0.559520138339,1.05223226496,-0.645574265818,F
0.35394105397,1.82996269805,0.398922026361,-1.52223131661,O
1.54163640493,0.478316068959,-0.666760327343,1.36717494756,X
-0.987620842341,0.337534288405,0.386934953004,1.99614391761,Z
-0.353462320307,-0.448433452071,-0.420520291568,0.606223206634,N
-0.275687122051,0.127910363851,0.877755572144,0.141774294303,6
0.448882070123,-0.0164103203039,-0.0414342913919,0.483096480304,6
-0.0437649578253,-0.878445916853,1.52507535186,0.00822316479269,Q
-0.0644155835746,0.080920574987,0.644715202274,0.393025120766,T
0.0150183089497,-1.62030091273,0.465865552616,1.63737662602,X
0.579715377177,-0.565645982402,-0.812128961966,1.53280260401,H
-0.324507167079,1.85335063636,-2.26860910203,-0.355131709073,F
-0.100246742541,-1.9546139579,0.132518774906,0.83692675288,K
0.275725087798,0.349561138652,-0.617722975053,0.675990898106,F
0.300486311556,-0.914367342324,-1.6046088239,-0.90545849944,P
-0.362382393314,0.708360644964,-0.388316739311,-2.32876299592,I
0.805330955425,0.0736168178539,0.481166223853,0.632620759249,Q
0.786095366054,0.0951374087988,-1.04996472851,1.82879833145,K
0.20781502657,1.40727518965,-1.04479960125,0.140207499487,2
1.80974963809,0.592023139186,-0.146214836643,-0.113817691749,J
0.190562146781,-2.88635875932,0.514364781284,-2.2081180574,F
0.844977118094,-0.164290184848,0.218672395512,0.0990115476933,D
0.195035085082,-0.649590655548,2.17166386104,0.453465558806,I
-0.0564333653869,1.75865043501,-0.448091017018,0.346784396043,C
-0.11260915388,-2.64245701436,-0.487309941502,-0.220507107741,K
-1.39531912204,0.573474013814,-0.0133236905274,-1.30707048628,C
-2.08027277833,0.0974981483635,0.321489166278,0.0126076722626,E
0.88317164615,0.490426984887,-0.799299286482,-0.699668792454,U
-0.138631966525,-1.41784482297,-0.199678277638,1.19929867533,V
-0.961579329566,1.16624685822,-1.12495332265,0.201727835778,D
1.30145347696,1.07711713668,0.56050246064,0.859991127179,U
0.0636793444679,-0.995532083484,0.879547223724,-0.0124713077028,R
-0.373381111798,0.982861169257,-0.0375341446861,-1.33785580601,G
1.49229222711,0.485490431128,0.129313292844,1.73356873962,Y
-0.908491526543,0.498234275772,-0.588843697186,-0.903956188452,8
1.13713975779,0.977509103934,-0.940993915461,0.149012866744,7
-1.04983803109,2.45342509904,1.23008741443,-2.06850760711,K
1.48519893861,-0.806453458123,-0.475087116613,0.936801368414,D
-0.790436911077,1.8238515301,0.470826739735,0.898781975943,J
2.02480808353,0.0322506496307,1.31529742078,-0.156432529592,S
0.379253002685,-1.05940924098,-1.13206803173,1.22229604428,I
2.40321605952,-1.79252836422,-0.917572680139,-0.88669297209,T
1.24997470755,1.49152996563,0.371475805897,-0.000464620420962,C
0.501130600702,-1.8524509796,1.11035434692,0.508864733821,E
1.10652128242,0.0981530997183,0.789793234562,1.19269254286,T
-0.540542595454,1.78256921968,0.0519310959987,0.463867655906,Q
-0.101979890355,0.981720222277,1.10699018111,-1.75226932921,M
0.632107381338,-0.761419236427,1.42793044112,-0.0469283588887,F
1.00977860887,-0.608379336968,-1.40510505648,-1.17505405942,F
-0.602747944659,-0.182503514402,-0.768163968379,1.26068635765,X
-0.0391054339894,-0.0695099824413,-1.35805194008,-0.292858620366,0
-0.345100573788,-0.179476870638,-0.904657664386,-0.0712867473108,T
-0.759495118894,0.225916245652,2.2358717609,-0.00448980823071,X
-1.6867705196,0.742275516539,0.48587599627,1.79850711251,Q
0.145697316417,0.805037295613,0.350361830434,-0.540234679436,O
2.48765369604,-0.147867121811,0.580688201183,-0.305696173077,S
0.38016591287,-0.592483279562,0.393693377794,-0.463216602736,M
0.96354902595,-1.55030192705,-0.944962257052,0.121546253521,K
-0.0403846130388,-0.312648567879,-1.19660390862,1.0750431857,S
0.938356628434,-0.235761104349,-0.0773603113055,1.16215015537,4
0.190303261201,-0.425472860755,0.362347382137,-0.688710660785,U
0.256419161128,0.0826694187979,-2.30275824842,-0.446115220145,6
0.690971664806,0.871498395659,0.948468891564,0.644683368429,7
-1.15778132548,0.0936961784472,-0.765272815741,-0.724766824934,Q
-0.295462233706,-0.832817149695,1.49020373854,-0.420786204612,F
0.132722962244,-1.25578038911,1.37000771682,1.14448991761,I
-0.111380676194,0.572076202947,1.8079619052,1.09020474362,N
0.178699745816,-1.60883234776,2.1746148394,-1.35173849821,6
1.20218256712,0.179582552204,0.202061214889,-0.731213132128,F
-0.674446571006,-0.184702666166,0.706721251292,0.718680803788,H
1.76553544644,-0.951931579911,0.320146510176,-1.15934952511,Z
-1.2478849863,-0.725490485007,0.541997606469,-0.126572143755,W
-1.1640445457,-0.647618961239,-0.550283265919,1.16494340443,H
1.81613255613,-0.393382465546,-1.21291011478,-0.317186597786,C
0.499882890819,-1.18363110139,-0.638619314755,-0.785336775967,Y
1.22849889391,1.25347911733,-0.221459415048,-0.0654131965162,H
1.01895127853,-0.423936860698,-1.72455343475,-0.823409084355,A
-0.169892938696,0.301071840312,1.40996063006,-0.516055941099,X
0.883067867689,0.950612783539,0.783765906001,0.776406924195,6
1.03277821333,-0.0929303289895,0.600042004986,0.173515461043,C
-0.249224588436,-0.0648201009871,-0.0127630546134,0.0304726487395,N
0.556590447301,1.97690140411,0.130668936682,2.71966409048,I
0.16107564162,-1.3149395378,-0.605192051164,-0.732212975124,S
-1.84206221975,0.0109146960347,-0.0132330195161,-0.29825942451,C
1.72723710088,1.67458417387,-0.988291322079,0.512445217364,H
-0.190386389574,-0.184385010197,1.16329213344,-1.05989578865,Y
0.69311133934,0.815751494672,-2.38869472458,-0.201710174422,J
-0.0621126729433,-0.00984964476467,0.658452659654,0.782909762977,X
0.880939751586,-0.707391129783,-0.750939055668,-0.0423814584647,Y
-0.592837623954,-0.700117210885,0.831351965158,-1.15891084185,V
1.62834979618,0.404618215489,0.0863343325974,0.278913544915,V
0.210544278316,-0.909438189136,0.903899753529,0.471579103734,0
0.033606494896,-0.882900260313,-0.345729265059,-0.317833493034,C
-0.0755744023429,-0.616260178437,-0.342470997941,0.850522271235,F
-1.26295070974,-0.167273237609,1.45780742884,-0.37563609476,H
-0.289513268133,-0.927606335239,0.950207336839,1.23406721349,R
1.34653227067,1.08338934179,-0.840822696227,0.525032166375,N
0.698212579575,-1.2635370225,0.0345888504173,-1.08271314806,U
-0.798004160565,-1.30179455306,-1.95685241187,-1.2841200757,H
0.042611218243,-0.175943187928,-1.01597727921,0.668173594623,B
1.52264922941,2.29139247927,1.5064450569,-0.448051016456,I
0.54911837215,-0.439673137424,0.651228776652,2.6480462772,4
0.119467771322,0.224633361843,-0.462936521536,1.41015553196,B
-0.323899441166,-0.115278120343,-2.24762512685,0.271304098854,S
-0.569092884953,1.86005610394,-2.5526005446,-0.433538185597,8
0.112111473607,-0.845797840143,1.00631020207,1.13883188261,S
-0.499492134991,0.91641467488,-1.04521512609,-0.50757820342,F
0.376336174588,0.764118507122,0.935520356664,-0.594284323631,E
0.0435519604575,-1.13311390808,1.83995995892,1.07689076788,8
0.08521566085,2.51096445751,-1.05481405994,0.673699680303,M
-1.78187926997,-1.08540212875,-0.0523621760075,-1.07072106964,S
0.895674400067,1.2217782908,0.354943949672,-2.72080073957,D
0.178964296545,-1.24036038336,0.216703259507,-0.931038265768,N
0.751110935945,-1.67754135722,-1.84529427201,0.472624179004,5
-0.174065305457,0.41737570589,0.67568579441,0.976129682648,8
0.469285344255,0.468042648048,0.740358197771,-3.17350880211,N
-0.414343091707,-0.847569597434,0.321460576581,-2.57576740455,T
0.947170681816,0.328539010454,0.194054760004,-0.530855170507,0
0.280983721958,2.21810968243,0.0430190102528,0.105970933337,M
1.36877536297,0.314364311301,0.237928036312,0.826479814371,X
-0.556653869652,0.677243772286,-0.0487451867473,0.481484592223,T
1.27535225202,-1.63660490059,-0.907082516741,-0.842150166534,H
0.354484776486,0.336961106409,-0.877360547161,1.94340295455,N
1.63041080339,-0.107837334831,-0.452669704243,0.511911011614,A
2.13082174199,-0.513612858636,-0.589272751532,0.270246731148,K
1.1330300851,-0.920498984072,-0.41147778905,-0.00125773317809,C
-0.022368446588,-0.165693213389,1.48750250694,-1.5609710846,X
-1.59781750388,-0.544169575971,0.565075786079,1.28817666767,U
-0.641428915759,0.376689595468,-0.153789313646,-0.512960526573,G
0.314357377289,-0.962541936748,-0.541512534494,-1.1561648896,Y
0.0883395556165,0.814274132271,-0.304655359037,0.792676034143,K
-0.241961771733,-0.629315403013,-2.21260233427,-0.374105157708,G
-1.18173491365,-0.596941681158,0.2743443978,0.273126365442,5
-0.216653074676,-0.736039143474,-0.695235903991,0.421187733859,O
-0.210084441042,0.708076753126,1.54565512016,-1.58704505966,G
-0.194803690607,-0.215578248302,0.691829450352,-0.0992752966404,Z
0.555034364088,-0.628948162163,-0.550886205331,-1.30358538455,Z
-0.00132553343873,0.234979080439,0.305587215001,1.17498471846,X
-0.505884715251,0.289074547151,-1.01753668504,0.086234836138,L
0.818458302751,-0.0774239427346,-1.53559692163,-0.727323013995,I
-0.739837815235,0.654747515967,0.775892880451,0.911725982352,L
-0.157668660717,0.0105765369843,-0.473290818785,-0.114977254557,J
1.582072755,1.21135077234,0.277131433192,0.637144296923,W
-0.704190048658,0.12787599735,1.05250272942,0.209073871078,B
-0.389367804328,-0.93291366124,-0.998024963481,0.563616911143,D
-0.558272131251,-0.161774896289,-1.53806659646,0.613443319356,G
-0.158497066494,1.34901324395,-0.475157789661,-1.0330587238,0
0.407671432137,0.254556508037,-1.56082456407,1.12562760798,F
-0.653921366863,0.0275790877175,-1.39629369836,0.913825226594,B
-2.57692549898,0.338165036668,0.519442976393,-2.30330714219,I
-0.842865347335,1.0821650933,-0.646397860835,-1.13500686925,U
-0.494181289099,0.104939493471,0.827236857824,1.05511433215,U
1.15576168508,-0.0660077704386,0.23605882151,0.309968188821,2
-0.687534473898,-0.0263544937825,0.106619281446,2.47490163593,N
0.649517559904,-1.17781051518,-0.954277458301,-0.339043658202,G
-0.423467777754,0.638837715089,-0.0390346575333,0.145446357589,Q
0.0827382882553,-0.472712215521,0.480072117744,2.01998684041,J
0.268893320742,-1.48484562253,-1.63763986608,-2.3255800776,I
-0.107129695053,-1.11241995795,-1.27069822508,0.848296771646,D
-1.04544077775,0.797202720191,-0.350622812646,-1.15411164074,B
0.419680914033,-1.20255497117,0.374432783263,-0.556201528434,F
0.203280886034,0.947044539757,0.990641967636,0.0618586714995,R
2.09212414836,0.906692467548,1.3274444574,1.09801998125,D
0.426330491605,0.77543138121,-0.540806606851,0.483395084815,G
1.65203944937,-0.887319814636,-2.17453333781,1.28661777145,D
1.01408518893,0.771958446614,0.391397552654,1.34960477211,D
-0.268733296954,0.145778431561,1.14838487859,-0.0558591686879,G
1.17460855008,0.611714412276,0.515178519961,-0.185847595552,M
-2.40501866212,-0.160283329726,2.32208248639,-0.944042520795,I
0.423191686836,0.0957867735118,-0.887767669303,-0.741621278186,W
-1.24207952376,0.371923550534,0.16677714031,1.0104893326,C
1.2934718078,1.14453036376,-1.4812669881,-0.441601572264,E
-1.12685300658,-1.03722648479,-0.239714171379,1.17321878409,7
-1.0622089135,1.19226182583,-0.77544757706,-1.22501175108,G
-0.372656417204,-0.485827702989,0.534654941088,-1.21224456369,A
-0.020036253405,-1.33303514247,2.18945039442,-0.24919015118,1
-0.577762744277,-0.389902047992,0.488137595884,0.626000837653,3
-0.766540645184,0.713716560555,-1.01825632674,1.88936116726,S
-1.73870003681,-0.336053519267,-0.992538495353,1.42120418055,A
-0.568215850256,-1.84814384541,0.863834662405,1.32228142724,4
1.32185817098,1.00887344786,0.254607528649,-1.34209930073,E
-1.44311819447,0.240571274358,0.792943937286,0.0736683310364,Z
0.440871905275,1.12257403393,-0.755518791048,-0.716928210258,I
1.51509585736,1.33547436495,-0.910115691199,0.0511775765034,1
2.02357956321,1.09680739934,-1.3481784049,0.264341887714,O
-0.361315167468,1.01065213956,2.55387890981,-0.0895751091802,H
-0.994547758775,-0.457568170876,2.21848280827,-1.2782514738,S
0.132032388144,-1.3051371475,-0.536163371291,-1.28005533132,T
1.16176432633,0.818181671369,0.0151191881992,0.283321533309,D
-1.03942080599,1.13451743559,-2.22579019681,0.0592040052355,G
-0.867388839047,0.398072218402,2.05379725736,0.734562840374,7
1.45300175913,0.569163454607,0.198247662356,0.46520554845,L
-0.0954282988118,0.428386420293,-0.405097533928,-1.39724911033,S
-1.17327031236,0.159077812036,1.9276511382,-0.210691347031,D
1.04396635963,-0.104110599839,-0.249275629159,-0.0207793012098,I
0.280528850972,1.60109135858,0.561331365945,0.868630989409,Q
-0.659952829242,-2.30316016277,0.248001069221,0.942725735947,5
0.790583884393,-0.983115534038,0.874530999569,0.809282002383,E
-1.17591092941,2.15198696697,-0.0809277136982,-0.431623621004,N
-0.261109738898,-0.516069628221,1.13538791735,-0.761319800575,V
0.703423839947,0.449614099105,-1.593578247,-1.15539989748,V
1.11645041825,-0.274068941169,-0.0297477874901,-0.433413276523,V
-0.357308670313,-0.529398311787,0.205417525617,0.108428490163,K
0.423229026993,2.08909611309,0.923674782142,1.50272651831,Q
0.217126083205,1.28236141456,-0.978428564074,0.263613449525,C
-0.443397941574,0.676989997986,0.638588633657,-0.873794918749,P
1.00534200238,0.682462254711,1.20027333585,0.193455111389,Q
1.37620985675,1.14804621775,-1.19493291425,-0.0246510549904,G
0.745346522906,-0.886025029683,-0.437063213681,2.12474074181,A
0.620059226462,-1.3714426877,0.722629755468,1.63796007884,A
0.00630699376911,-1.33134152729,0.0649616494499,-0.572398251742,A
-0.198477349779,0.684455814174,-0.147475221075,0.581648940506,8
0.681178436604,0.283488752572,-0.20125716997,-0.837272455076,Y
-3.72686372556,2.15263217662,0.986711235344,-1.27395629167,E
1.23296534957,-0.872075211571,1.12573394106,-1.26969198429,1
1.68071777569,-0.795061674656,0.429541561971,0.907959685749,1
0.0126033461146,-0.559557999613,1.17009301533,-0.755084321136,D
0.478687852114,-0.923803097176,-1.62141331544,1.12210892346,E
0.654912901411,0.0515714367429,2.0161479636,0.652618167303,4
-0.840524554435,-0.155627932446,0.992245693988,0.818994762669,T
0.167651456358,-0.126483159859,-0.2159230909,-0.551816953755,9
-1.69486905349,-0.251793821628,0.643791694262,1.05148438879,X
1.15891064075,1.19204131316,-0.474725241124,-1.1885329973,X
-0.359609404441,-0.742869703536,-1.43423198616,-0.412530336918,I
0.527893710782,0.0840680255476,2.36852964741,-0.00302369910935,B
0.388307345228,0.969655421373,-0.16239111452,-0.256349189716,J
-0.270080229648,-1.25575148996,-0.356178529128,1.23140641525,D
0.0820128039793,-0.523347238177,-0.29892608064,-2.25924648718,F
-1.40152899868,0.293567238208,0.915068680577,-0.697823682964,1
-0.34203915437,0.204837022753,0.965391319534,0.21957721666,N
1.58845583063,-0.269371964148,-0.298398891617,-0.0173215631696,S
0.367102716772,-0.208086567685,-0.251701415964,-0.522192758844,G
0.197511460601,-0.502179218169,-1.73685418123,1.23451645845,L
1.55252757473,-1.33235367105,-0.227917886077,-0.817040668057,I
0.304381622491,1.40660303091,0.373171731372,0.446836979475,6
-1.40555861862,-0.701879470135,1.7938014939,-0.370494730707,U
-0.290145817461,0.466116593833,1.01992419248,-0.0913182440873,Y
-0.0461043106532,0.873557369774,0.660301204101,0.463093389561,E
-1.57701158808,-2.11928449832,1.8056211286,-0.283501178844,S
0.34037236652,0.382560935847,0.000310750462007,0.452416589048,G
1.61748513305,0.325101331381,-0.56004210719,0.944086448958,O
0.268348057071,-0.373019728317,0.433140418073,-0.868285773218,L
0.599410556722,-1.05300636777,-0.0612465004706,0.890921720842,F
-1.76732355314,0.564682563134,-0.274611661673,-0.174666490025,R
0.00758863980265,1.50644674792,1.90347761211,0.416104168602,G
-0.109962464506,-0.92011662808,1.82319172674,-1.42793478629,5
0.645940278964,0.441283164828,0.724278886156,0.72679455762,R
1.18991277757,-0.453600708269,1.20712924318,-0.241784995613,T
1.20958260767,0.65135204117,0.384909738967,0.560129899922,N
-0.835033146253,0.186814148387,0.0994207791387,-0.540764053646,7
0.923118167978,-1.34952513551,1.98628884937,1.09994393543,U
-0.169421148516,1.09333515534,-0.0476520705247,-0.0857051252725,L
-0.367094822957,-0.764236642365,0.525876450542,0.358030321448,O
-1.1500069318,0.824940600187,-0.871590899842,0.058123757859,X
1.49739986205,-0.819334159838,0.0173922939101,-0.0373138831218,E
-0.317808432798,1.23565305224,0.129119462254,-0.750614454962,L
0.89532447686,1.73828940595,-0.789496165367,1.56141462002,R
-2.32337594373,-0.0864840810099,-0.937811232637,0.975500070851,Z
0.749856964401,-1.46987067396,2.67443377359,-0.835017756629,L
-0.631610955098,-0.828862135897,-0.120593931393,-1.00073677846,6
-0.722216454,-0.507615853758,0.252700306067,-0.196934531941,R
-1.12139973048,-0.830073503932,-1.55615056655,1.3721124891,F
1.25533425487,-0.09154850985,-1.09204964199,1.43161043377,6
-2.088979558,-1.03384018998,-0.175709666863,-0.0449589141002,H
-0.593835822312,-0.125592399728,-0.148472855001,0.824293452333,J
-0.853371415484,-1.05039203696,-1.63655218727,-0.531499124856,X
0.184960336992,0.724280895102,-1.30361378129,0.0427831967716,B

In [72]:
result = pd.read_csv("examples/ex6.csv")
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

If you want to read only a small number of rows (avoiding reading the entire file),
specify that with nrows

In [73]:
pd.read_csv("examples/ex6.csv", nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

To read a file in pieces, specify a
chunksize as a number of rows:

In [74]:
pd.read_csv("examples/ex6.csv", chunksize=1000)

The
object returned by
allows you to iterate over
TextFileReader
pandas.read_csv
the parts of the file according to the chunksize. For example, we can iterate over
.csv, aggregating the value counts in the
column, like so
ex6
"key"

In [75]:
chunker = pd.read_csv("examples/ex6.csv", chunksize=1000)

tot = pd.Series([],dtype='int64')
for piece in chunker:
    tot = tot.add(piece["key"].value_counts(), fill_value=0)
tot = tot.sort_values(ascending=False)
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

is also equipped with a
method that enables you to read
TextFileReader
get_chunk
pieces of an arbitrary size.

The chunksize argument is a memory-saving feature used when you need to process a massive CSV file that is too large to fit into your computer's RAM.

Instead of trying to load the entire file into one giant DataFrame all at once, chunksize tells pandas to load the data in smaller, bite-sized pieces (chunks) of a specific number of rows.

When you use chunksize, pd.read_csv() does not return a DataFrame. Instead, it returns a TextFileReader object. You can think of this object as a bookmark in the file that waits for you to tell it to read the next set of rows.

Here are the three main ways to use it.

Example 1: Looping through a massive file
This is the most common use case. You loop over the TextFileReader. In each step of the loop, pandas gives you a standard DataFrame containing exactly the number of rows you specified

In [76]:
import pandas as pd

# Let's pretend 'massive_data.csv' has 10 million rows.
# We will read it 100,000 rows at a time.
chunker = pd.read_csv("examples/ex6.csv", chunksize=1000)

# 'chunker' is a TextFileReader object
print(type(chunker)) 
# Output: <class 'pandas.io.parsers.readers.TextFileReader'>

# Loop through the file piece by piece
for chunk in chunker:
    # 'chunk' is just a normal pandas DataFrame!
    # You can do normal pandas operations on it here.
    
    # Example: clean the data and save it to a database
    print(f"Processing a chunk with {len(chunk)} rows...")

<class 'pandas.io.parsers.readers.TextFileReader'>
Processing a chunk with 1000 rows...
Processing a chunk with 1000 rows...
Processing a chunk with 1000 rows...
Processing a chunk with 1000 rows...
Processing a chunk with 1000 rows...
Processing a chunk with 1000 rows...
Processing a chunk with 1000 rows...
Processing a chunk with 1000 rows...
Processing a chunk with 1000 rows...
Processing a chunk with 1000 rows...

Example 2: The get_chunk() method
As you mentioned in your previous message, the TextFileReader has a get_chunk() method. This is useful if you don't want to loop through the whole file, but just want to pull a specific number of rows on demand.

In [77]:
chunker = pd.read_csv("examples/ex6.csv", chunksize=1000)

# Pull the first 1000 rows
piece_1 = chunker.get_chunk() 

# Pull the NEXT 1000 rows (it remembers where it left off)
piece_2 = chunker.get_chunk()

# You can also override the chunksize for a single pull
piece_3 = chunker.get_chunk(50) # Pulls just 50 rows

Example 3: A Practical Aggregation
How do you calculate something like the total sum of a column if you can't load the whole file into memory? You calculate the sum of each chunk, and add those sums together.


Summary
Without chunksize: Pandas loads the entire file into memory at once. Fast, but crashes if the file is larger than your RAM.

With chunksize: Pandas loads X rows into memory, lets you process them, clears them from memory, and then loads the next X rows. Slower, but can process files of infinite size.

#### Writing Data to Text Format

In [78]:
data = pd.read_csv("examples/ex5.csv")

data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [79]:
data.to_csv("examples/ex5_out.csv")

In [80]:
!cat "examples/ex5_out.csv"

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

Other delimiters can be used, of course (writing to
so it prints the text
sys.stdout
result to the console rather than a file):

In [81]:
import sys
data.to_csv(sys.stdout, sep="|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

Missing values appear as empty strings in the output. You might want to denote them
by some other sentinel value:

In [82]:
data.to_csv(sys.stdout, na_rep="NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

With no other options specified, both the row and column labels are written. Both of
these can be disabled:

In [83]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [84]:
data.to_csv(sys.stdout, index=False, columns=["a", "b", "c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [85]:
data.to_csv(sys.stdout, index=False, columns=["a", "b"]) # Can specify columns to include

a,b
1,2
5,6
9,10

#### Working with Delimited Formats

It’s not uncommon to receive a file with one or more malformed lines that trip up
pandas.read_csv. To illustrate the basic tools, consider a small CSV file:

In [86]:
!cat examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

For any file with a single-character delimiter, you can use Python’s built-in
csv
module. To use it, pass any open file or file-like object to
csv.reader

In [87]:
import csv
f = open("examples/ex7.csv")
reader = csv.reader(f)
for line in reader:
    print(line)

f.close()

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

Iterating through the reader like a file yields lists of values with any quote characters
removed:

From there, it’s up to you to do the wrangling necessary to put the data in the form
that you need. Let’s take this step by step. First, we read the file into a list of lines:

In [88]:
with open("examples/ex7.csv") as f:
    lines = list(csv.reader(f))

header, values = lines[0], lines[1:]

print(header)
print(values)

['a', 'b', 'c']
[['1', '2', '3'], ['1', '2', '3']]

In [89]:
list(zip(*values))

[('1', '1'), ('2', '2'), ('3', '3')]

In [90]:
list(zip(header, zip(*values)))

[('a', ('1', '1')), ('b', ('2', '2')), ('c', ('3', '3'))]

In [91]:
data_dict = dict(zip(header, zip(*values)))

data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

(beware that this will use a lot of memory on large
files), which transposes rows to columns:

CSV files come in many different flavors. To define a new format with a different
delimiter, string quoting convention, or line terminator, we could define a simple
subclass of
csv.Dialect

In [92]:
import types,sys
class my_dialect(csv.Dialect):
    lineterminator = "\n"
    delimiter = ";"
    quotechar = '"'
    quoting = csv.QUOTE_ALL

    # There is also a csv.QUOTE_NONNUMERIC option, which will quote text but leave actual numbers unquoted. However, since you are passing your numbers as strings—like "1" instead of 1—Python will treat them as text and quote them anyway if you use that option

    #  QUOTE_MINIMAL tells Python to only add quotes when it is absolutely mathematically necessary to prevent the CSV file from breaking.
with open("examples/ex7.csv") as f:
    reader = csv.reader(f, dialect=my_dialect)

print(isinstance(reader, types.GeneratorType)) #Not a generator
print(sys.getsizeof(reader))

False
104

We could also give individual CSV dialect parameters as keywords to
csv.reader
without having to define a subclass:

In [93]:
with open("examples/ex7.csv") as f:
    reader = csv.reader(f, delimiter="|", quotechar='"')

In [94]:
with open("examples/mydata.csv", "w") as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(("one", "two", "three"))
    writer.writerow(("1", "2", "3"))
    writer.writerow(("4", "5", "6"))
    writer.writerow(("7", "8", "9"))

In [95]:
!cat examples/mydata.csv

"one";"two";"three"
"1";"2";"3"
"4";"5";"6"
"7";"8";"9"

#### JSON Data

In [96]:
obj = """
{"name": "Wes",
"cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
"pet": null,
"siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
{"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""


import json
result = json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [97]:
asjson = json.dumps(result)
asjson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

you can pass a list of
dictionaries (which were previously JSON objects) to the DataFrame constructor and
select a subset of the data fields

In [98]:
siblings = pd.DataFrame(result["siblings"], columns=["name", "age"])
siblings

    name  age
0  Scott   34
1  Katie   42

The pandas.read_json
can automatically convert JSON datasets in specific arrangements
into a Series or DataFrame. For example:

In [99]:
!cat examples/example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

The default options for
assume that each object in the JSON array
pandas.read_json
is a row in the table:

In [100]:
data = pd.read_json("examples/example.json")
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

If you want to read the JSON data into a Series, you can pass the orient argument:

In [101]:
data = pd.read_json("examples/example.json", orient="records")
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

#### export data from pandas to JSON

In [102]:
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

#### XML and HTML: Web Scraping

pandas has a built-in function,
pandas.read_html, which uses all of these libraries to
automatically parse tables out of HTML files as DataFrame objects

In [103]:
tables = pd.read_html("examples/fdic_failed_bank_list.html")
len(tables)

1

In [104]:
failure_report = tables[0]
failure_report.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

The
pandas.read_html function has a number of options, but by default it searches

for and attempts to parse all tabular data contained within
<table> tags. The result is

a list of DataFrame objects:

In [105]:
close_timestamps = pd.to_datetime(failure_report["Closing Date"])
close_timestamps

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[us]

In [106]:
close_timestamps.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, Length: 15, dtype: int64

#### Parsing XML with lxml.objectify

pandas.read_html function, which uses either lxml or Beautiful
Soup under the hood to parse data from HTML. XML and HTML are structurally
similar, but XML is more general.

an example of how to use lxml to
parse data from a more general XML format.

In [ ]:
"""<INDICATOR>
<INDICATOR_SEQ>373889</INDICATOR_SEQ>
<PARENT_SEQ></PARENT_SEQ>
<AGENCY_NAME>Metro-North Railroad</AGENCY_NAME>
<INDICATOR_NAME>Escalator Availability</INDICATOR_NAME>
<DESCRIPTION>Percent of the time that escalators are operational
systemwide. The availability rate is based on physical observations performed
the morning of regular business days only. This is a new indicator the agency
began reporting in 2009.</DESCRIPTION>
<PERIOD_YEAR>2011</PERIOD_YEAR>
<PERIOD_MONTH>12</PERIOD_MONTH>
<CATEGORY>Service Indicators</CATEGORY>
<FREQUENCY>M</FREQUENCY>
<DESIRED_CHANGE>U</DESIRED_CHANGE>
<INDICATOR_UNIT>%</INDICATOR_UNIT>
<DECIMAL_PLACES>1</DECIMAL_PLACES>
<YTD_TARGET>97.00</YTD_TARGET>
<YTD_ACTUAL></YTD_ACTUAL>
<MONTHLY_TARGET>97.00</MONTHLY_TARGET>
<MONTHLY_ACTUAL></MONTHLY_ACTUAL>
</INDICATOR>
"""

from lxml import objectify

path = "datasets/mta_perf/Performance_MNR.xml"

with open(path) as f:
    parsed = objectify.parse(f)

root = parsed.getroot()

root

root.INDICATOR returns a generator yielding each
XML element. For
<INDICATOR>
each record, we can populate a dictionary of tag names (like
_ACTUAL) to data
YTD
values (excluding a few tags) by running the following code:

In [110]:
data = []

skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ",
"DESIRED_CHANGE", "DECIMAL_PLACES"]

for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval
    data.append(el_data)

data

[{'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 1,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.9,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.9},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 2,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.0,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 95.0},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 3,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.3,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.9},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 4,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.8,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 98.3},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 5,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.6,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 95.8},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 6,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.2,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 94.4},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 7,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.2,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.0},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 8,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.2,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.4},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 9,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 95.9,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 93.7},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 10,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.0,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.4},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 11,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.1,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 96.9},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2008,
  'PERIOD_MONTH': 12,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 95.0,
  'YTD_ACTUAL': 96.0,
  'MONTHLY_TARGET': 95.0,
  'MONTHLY_ACTUAL': 95.1},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 1,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 92.6,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 92.6},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 2,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 94.6,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 96.8},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 3,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 95.4,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 96.9},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 4,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 95.9,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 97.1},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 5,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.2,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 97.8},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 6,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.4,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 97.3},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 7,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.5,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 96.7},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 8,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.4,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 95.7},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 9,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.3,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 96.1},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 10,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.2,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 94.8},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 11,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.1,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 95.7},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2009,
  'PERIOD_MONTH': 12,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.2,
  'YTD_ACTUAL': 96.0,
  'MONTHLY_TARGET': 96.2,
  'MONTHLY_ACTUAL': 95.0},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 1,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 98.0,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 98.0},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 2,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 95.6,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 93.0},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 3,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.1,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 96.9},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 4,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.6,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 98.1},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 5,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.8,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 97.6},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 6,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.9,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 97.4},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 7,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.9,
  'MONTHLY_TARGET': 96.3,
  'MONTHLY_ACTUAL': 96.6},
 {'AGENCY_NAME': 'Metro-North Railroad',
  'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
  'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
  'PERIOD_YEAR': 2010,
  'PERIOD_MONTH': 8,
  'CATEGORY': 'Service Indicators',
  'FREQUENCY': 'M',
  'INDICATOR_UNIT': '%',
  'YTD_TARGET': 96.3,
  'YTD_ACTUAL': 96.9,
  'MONTHLY_TARGET': 96.3,

In [111]:
perf = pd.DataFrame(data)

perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

#### pandas’s pandas.read_xml function turns this process into a one-line expression:

In [112]:
perf2 = pd.read_xml(path)
perf2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

#### Binary Data Formats

#### One simple way to store (or serialize) data in binary format is using Python’s built-in module. pandas objects all have a method to_pickle that writes the data to disk in pickle format

In [113]:
frame = pd.read_csv("examples/ex1.csv")

frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [114]:
frame.to_pickle("examples/frame_pickle")

In [115]:
pd.read_pickle("examples/frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

#### is recommended only as a short-term storage format. 
The
pickle
problem is that it is hard to guarantee that the format will be
stable over time; an object pickled today may not unpickle with a
later version of a library. pandas has tried to maintain backward
compatibility when possible, but at some point in the future it may
be necessary to “break” the pickle format

pandas has built-in support for several other open source binary data formats, such
as HDF5, ORC, and Apache Parquet. For example, if you install the pyarrow package you can read Parquet files with pandas.read_parquet:

In [116]:
fec = pd.read_parquet("datasets/fec/fec.parquet")

fec.head()

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
0,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,250.0,20-JUN-11,NaN,NaN,NaN,SA17A,736166
1,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,50.0,23-JUN-11,NaN,NaN,NaN,SA17A,736166
2,C00410118,P20002978,"Bachmann, Michelle","SMITH, LANIER",LANETT,AL,368633403,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,05-JUL-11,NaN,NaN,NaN,SA17A,749073
3,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253,NONE,RETIRED,250.0,01-AUG-11,NaN,NaN,NaN,SA17A,749073
4,C00410118,P20002978,"Bachmann, Michelle","WARDENBURG, HAROLD",HOT SPRINGS NATION,AR,719016467,NONE,RETIRED,300.0,20-JUN-11,NaN,NaN,NaN,SA17A,736166

#### Reading Microsoft Excel Files

In [119]:
xlsx = pd.ExcelFile("examples/ex1.xlsx")
xlsx

In [120]:
xlsx.sheet_names

['Sheet1']

In [121]:
xlsx.parse(sheet_name="Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

This Excel table has an index column, so we can indicate that with the
index_col
argument:

In [122]:
xlsx.parse(sheet_name="Sheet1", index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

If you are reading multiple sheets in a file, then it is faster to create the
pandas.Excel
File, but you can also simply pass the filename to
pandas.read_excel

In [124]:
frame = pd.read_excel("examples/ex1.xlsx", sheet_name="Sheet1")
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

#### To write pandas data to Excel format, you must first create an ExcelWriter, then write data to it using the pandas object’s to_excel method:

In [127]:
writer = pd.ExcelWriter("examples/ex1_out.xlsx")
frame.to_excel(writer,sheet_name="Sheet1")
writer.close()

##### You can also pass a file path to to_excel and avoid the ExcelWriter:

In [128]:
frame.to_excel("examples/ex2_out.xlsx", sheet_name="Sheet1")

#### Using HDF5 Format

HDF5 is a respected file format intended for storing large quantities of scientific array
data. It is available as a C library, and it has interfaces available in many other languages,
including Java, Julia, MATLAB, and Python. The “HDF” in HDF5 stands for
hierarchical data format. Each HDF5 file can store multiple datasets and supporting
metadata. Compared with simpler formats, HDF5 supports on-the-fly compression
with a variety of compression modes, enabling data with repeated patterns to be
stored more efficiently. HDF5 can be a good choice for working with datasets that
don’t fit into memory, as you can efficiently read and write small sections of much
larger arrays.

While it’s possible to directly access HDF5 files using either the PyTables or h5py
libraries, pandas provides a high-level interface that simplifies storing Series and
DataFrame objects. The HDFStore class works like a dictionary and handles the
low-level details:

In [132]:
frame = pd.DataFrame({"a" : np.random.standard_normal(100)})

frame

           a
0  -1.981207
1   1.970485
2   0.771750
3  -0.722190
4  -0.428265
..       ...
95  0.248347
96 -0.639596
97  0.142559
98 -0.257533
99  0.688220

[100 rows x 1 columns]

In [133]:
store = pd.HDFStore("examples/mydata.h5")
store["obj1"] = frame
store["obj1"]

           a
0  -1.981207
1   1.970485
2   0.771750
3  -0.722190
4  -0.428265
..       ...
95  0.248347
96 -0.639596
97  0.142559
98 -0.257533
99  0.688220

[100 rows x 1 columns]

Objects contained in the HDF5 file can then be retrieved with the same dictionarylike
API:

In [134]:
store["obj1_col"] = frame["a"]

store["obj1_col"]

0    -1.981207
1     1.970485
2     0.771750
3    -0.722190
4    -0.428265
        ...
95    0.248347
96   -0.639596
97    0.142559
98   -0.257533
99    0.688220
Name: a, Length: 100, dtype: float64

In [135]:
store

<class 'pandas.HDFStore'>
File path: examples/mydata.h5

#### HDFStore supports two storage schemas, "fixed" and "table" (the default is "fixed"). The latter is generally slower, but it supports query operations using a special syntax:

In [136]:
store.put("obj2", frame, format="table")
store["obj2"]

           a
0  -1.981207
1   1.970485
2   0.771750
3  -0.722190
4  -0.428265
..       ...
95  0.248347
96 -0.639596
97  0.142559
98 -0.257533
99  0.688220

[100 rows x 1 columns]

In [137]:
store.select("obj2", where=["index >= 10 and index <= 15"])

           a
10  2.211534
11  0.376382
12 -2.404207
13  1.253934
14 -0.376005
15 -0.639358

In [138]:
store.close()

The put is an explicit version of the
store["obj2"] = frame method but allows us to 
set other options like the storage format.

The pandas.read_hdf function gives you a shortcut to these tools:

In [139]:
frame.to_hdf("examples/mydata.h5", key="obj3", format="table")

In [140]:
pd.read_hdf("examples/mydata.h5", key="obj3", where=["index >= 10 and index <= 15"])

           a
10  2.211534
11  0.376382
12 -2.404207
13  1.253934
14 -0.376005
15 -0.639358

HDF5 is not a database. It is best suited for write-once, read-many
datasets. While data can be added to a file at any time, if multiple
writers do so simultaneously, the file can become corrupted.

#### Interacting with Web APIs

In [142]:
import requests

url = "https://api.github.com/repos/pandas-dev/pandas/issues"

resp = requests.get(url)
resp.raise_for_status()

resp

#### It’s a good practice to always call raise_for_status after using requests.get to check for HTTP errors.

In [ ]:
data = resp.json()

data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/66831',
  'id': 5181738060,
  'node_id': 'PR_kwDOAA0YD88AAAABAJI0pA',
  'number': 66831,
  'title': 'BUG: reindex applying method to the columns axis',
  'user': {'login': 'sanderland',
   'id': 48946947,
   'node_id': 'MDQ6VXNlcjQ4OTQ2OTQ3',
   'avatar_url': 'https://avatars.githubusercontent.com/u/48946947?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/sanderland',
   'html_url': 'https://github.com/sanderland',
   'followers_url': 'https://api.github.com/users/sanderland/followers',
   'following_url': 'https://api.github.com/users/sanderland/following{/other_user}',
   'gists_url': 'https://api.github.com/users/sanderland/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/sanderland/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/sanderland/subscriptions',
   'organizations_url': 'https://api.github.com/users/sanderland/orgs',
   'repos_url': 'https://api.github.com/users/sanderland/repos',
   'events_url': 'https://api.github.com/users/sanderland/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/sanderland/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-08-18T12:24:04Z',
  'updated_at': '2026-08-18T12:24:04Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'CONTRIBUTOR',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/66831',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/66831',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/66831.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/66831.patch',
   'merged_at': None},
  'body': 'Note: this is a very old issue, with recent docstring changes clarifying the somewhat confusing behaviour.\r\nIf this is no longer wanted, please close the original issue.\r\n\r\n## Background \r\n\r\nSee pandas-dev/pandas#31002, tldr:\r\n\r\n`_reindex_axes` passed a single `method` to every axis being reindexed, so when a\r\nDataFrame was reindexed on both axes at once a column missing from the original\r\nframe was filled from whichever column sorted next to it: `bfill` and `ffill`\r\ndisagreed on the same data, and `nearest` raised `TypeError` on string labels.\r\n\r\n## Fix\r\n\r\n`method`, `limit` and `tolerance` now apply to the index only when more than one\r\naxis is reindexed. \r\n\r\nSingle-axis `df.reindex(columns=..., method=...)` is unchanged.\r\n\r\n## Checks\r\n\r\n- [x] closes pandas-dev/pandas#31002\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- (n/a) Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n- [x] I have reviewed and followed all the [contribution guidelines](https://pandas.pydata.org/docs/dev/development/contributing.html)\r\n\r\nCheck exactly one of the following, per the [automated contributions policy](https://pandas.pydata.org/docs/dev/development/contributing.html#automated-contributions-policy):\r\n\r\n- [ ] I did **not** use AI to develop this pull request.\r\n- [x] I used AI to develop this pull request. I prompted it to follow `AGENTS.md`, I have reviewed and understood every change, and I have described above how I used it and exactly which tool, model version, and effort setting — e.g. `claude opus 4.8 (xhigh)`, not just `claude`.\r\n\r\nDeveloped with Opus 5, with review by GPT 5.6 Sol and me\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66830',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66830/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66830/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66830/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/66830',
  'id': 5177672453,
  'node_id': 'PR_kwDOAA0YD88AAAABAF4AXg',
  'number': 66830,
  'title': 'BUG: int64 ndarray input to PeriodArray read as a literal calendar year',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-08-18T03:13:48Z',
  'updated_at': '2026-08-18T03:13:48Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'MEMBER',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/66830',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/66830',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/66830.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/66830.patch',
   'merged_at': None},
  'body': 'Stacked on GH-66829, which is the first of the two commits here — review that one first. I will rebase this onto main once it goes in.\n\nEvery path that reads an integer as a calendar year parses `str(value)`: the `Period` scalar constructor, the object-dtype array path in `extract_ordinals`, and (since GH-66249) the masked and arrow integer arrays routed through it. The int64 ndarray path added in GH-64158 instead reads the integer as a literal year. The two agree only for four-digit years:\n\n```python\n>>> pd.PeriodIndex(np.array([20000101]), freq="D")     # int64 ndarray\nPeriodIndex([\'20000101-01-01\'], dtype=\'period[D]\')\n>>> pd.PeriodIndex(np.array([20000101], dtype=object), freq="D")\nPeriodIndex([\'2000-01-01\'], dtype=\'period[D]\')\n>>> pd.Period(20000101, freq="D")\nPeriod(\'2000-01-01\', \'D\')\n```\n\nso an NA, or the choice of integer container, changed the values:\n\n```python\n>>> pd.Series([200701, 200702], dtype="period[M]").tolist()\n[Period(\'200701-01\', \'M\'), Period(\'200702-01\', \'M\')]\n>>> pd.Series([200701, None], dtype="period[M]").tolist()\n[Period(\'2007-01\', \'M\'), NaT]\n>>> pd.array(pd.array([200701, 200702], dtype="Int64"), dtype="period[M]").tolist()\n[Period(\'2007-01\', \'M\'), Period(\'2007-02\', \'M\')]\n```\n\nThis keeps the specialized conversion for four-digit values, where the two interpretations are the same and the GH-64158 speedup applies (`np.arange(1000, 2000).repeat(1000)` is unchanged at 6.5 ms), and parses everything else. Values the scalar constructor rejects — `999`, `0`, `-5`, `100000` — are now rejected here with the same error, which replaces the int32 year guard from GH-66248.\n\nuint64 input above int64 max wrapped in the `astype(np.int64)` before any of that, so `PeriodArray._from_sequence(np.array([2**64 - 5], dtype=np.uint64), dtype="period[D]")` gave `Period(\'-5-01-01\')` and `2**63` gave `NaT`. Those go through the object path now and raise `OutOfBoundsDatetime` like `Period(2**64 - 5, freq="D")` does.\n\nWith the interpretations aligned, the deprecation message can name the one-liner that keeps today\'s behavior (`data.astype(str)`) instead of telling the user to build the `Period` objects themselves.\n\nNo whatsnew: the divergence arrived in GH-64158 and the uint64 wrap in GH-64231, both unreleased in 3.1.0.dev, as is the deprecation whose message this touches (GH-65173).\n\nOne test changes shape: `Series([0, 1000, 2000, iNaT], dtype="period[D]")` used the literal-year reading to accept year 0, which `Period(0, freq="D")` has always rejected; the test is about the `iNaT` sentinel, so it keeps that and uses years the scalar constructor accepts.\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66830/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66830/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66829',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66829/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66829/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66829/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/66829',
  'id': 5177668899,
  'node_id': 'PR_kwDOAA0YD88AAAABAF30xA',
  'number': 66829,
  'title': 'BUG: Period silently returned the 1970 epoch on ordinal overflow',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-08-18T03:13:16Z',
  'updated_at': '2026-08-18T03:13:16Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'MEMBER',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/66829',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/66829',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/66829.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/66829.patch',
   'merged_at': None},
  'body': '`get_period_ordinal` is `noexcept`, so the `OverflowError` that `np_datetime.c` raises for an ordinal that does not fit in int64 was discarded — Cython printed `Exception ignored in: \'pandas._libs.tslibs.period.get_period_ordinal\'` to stderr — and ordinal 0 was returned in its place:\n\n```python\n>>> pd.Period("2300-01-01", freq="ns")\nPeriod(\'1970-01-01 00:00:00.000000000\', \'ns\')\n\n>>> pd.PeriodIndex(["2000-01-01", "2300-01-01", "2001-01-01"], freq="ns").asi8\narray([946684800000000000,                  0, 978307200000000000])\n\n>>> pd.date_range("2300-01-01", periods=2, freq="D", unit="s").to_period("ns")\nPeriodIndex([\'1970-01-01 00:00:00.000000000\', \'1970-01-01 00:00:00.000000000\'], dtype=\'period[ns]\')\n```\n\nAll three now raise `OutOfBoundsDatetime`. Found while working through the follow-up on GH-66248, whose int32 year guard covers a different half of the same problem.\n\nValidating before converting rather than propagating the error out of `get_period_ordinal`: making it `except? -1 nogil` costs ~50% on `PeriodIndex(integer_array)` and ~30% on `to_period`, which is more than this is worth. Whether a freq is fine enough to overflow at all, and which years are in bounds whatever the rest of the date is, depend only on the freq, so `from_calendar_ordinals` and `dt64arr_to_periodarr` hoist that out of their loops and pay one year comparison per element; only the boundary years take the full `check_dts_bounds`. On 1M values:\n\n| | main | PR |\n|---|---|---|\n| `PeriodIndex(int_array, freq="D")` | 6.6 ms | 6.5 ms |\n| `to_period("M")` | 12.1 ms | 13.0 ms |\n| `to_period("D")` | 14.8 ms | 15.2 ms |\n| `to_period("s")` | 16.3 ms | 16.7 ms |\n| `to_period("ns")` | 18.2 ms | 18.3 ms |\n\nTwo notes on the diff:\n\n- `period_ordinal` never initialized `dts.as` — harmless while nothing read it, but the bounds check does, so it needs a `memset` (Cython cannot name an `as` field).\n- The GH-66550 test for `to_period("ns")` on a wall time sitting exactly on the NaT sentinel now gets `Out of bounds nanosecond timestamp` instead of `underflows past`: the value is rejected as out of bounds for the freq before it reaches an ordinal. Still `OutOfBoundsDatetime`, so the guarantee that test was written for holds.\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66829/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66829/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66828',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66828/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66828/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66828/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/66828',
  'id': 5177525064,
  'node_id': 'PR_kwDOAA0YD88AAAABAFwc5w',
  'number': 66828,
  'title': 'BUG: TypeError in tz_convert/tz_localize with a keyless ZoneInfo (GH#64379)',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 32815646,
    'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression',
    'name': 'Regression',
    'color': 'e11d21',
    'default': False,
    'description': 'Functionality that used to work in a prior pandas version'},
   {'id': 60458168,
    'node_id': 'MDU6TGFiZWw2MDQ1ODE2OA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timezones',
    'name': 'Timezones',
    'color': '5319e7',
    'default': False,
    'description': 'Timezone data dtype'}],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2026-08-18T02:50:40Z',
  'updated_at': '2026-08-18T11:08:51Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'MEMBER',
  'issue_field_values': [],
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/66828',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/66828',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/66828.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/66828.patch',
   'merged_at': None},

In [144]:
data[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831/events',
 'html_url': 'https://github.com/pandas-dev/pandas/pull/66831',
 'id': 5181738060,
 'node_id': 'PR_kwDOAA0YD88AAAABAJI0pA',
 'number': 66831,
 'title': 'BUG: reindex applying method to the columns axis',
 'user': {'login': 'sanderland',
  'id': 48946947,
  'node_id': 'MDQ6VXNlcjQ4OTQ2OTQ3',
  'avatar_url': 'https://avatars.githubusercontent.com/u/48946947?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/sanderland',
  'html_url': 'https://github.com/sanderland',
  'followers_url': 'https://api.github.com/users/sanderland/followers',
  'following_url': 'https://api.github.com/users/sanderland/following{/other_user}',
  'gists_url': 'https://api.github.com/users/sanderland/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/sanderland/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/sanderland/subscriptions',
  'organizations_url': 'https://api.github.com/users/sanderland/orgs',
  'repos_url': 'https://api.github.com/users/sanderland/repos',
  'events_url': 'https://api.github.com/users/sanderland/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/sanderland/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 'labels': [],
 'state': 'open',
 'locked': False,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2026-08-18T12:24:04Z',
 'updated_at': '2026-08-18T12:24:04Z',
 'closed_at': None,
 'assignee': None,
 'author_association': 'CONTRIBUTOR',
 'issue_field_values': [],
 'type': None,
 'active_lock_reason': None,
 'draft': False,
 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/66831',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/66831',
  'diff_url': 'https://github.com/pandas-dev/pandas/pull/66831.diff',
  'patch_url': 'https://github.com/pandas-dev/pandas/pull/66831.patch',
  'merged_at': None},
 'body': 'Note: this is a very old issue, with recent docstring changes clarifying the somewhat confusing behaviour.\r\nIf this is no longer wanted, please close the original issue.\r\n\r\n## Background \r\n\r\nSee pandas-dev/pandas#31002, tldr:\r\n\r\n`_reindex_axes` passed a single `method` to every axis being reindexed, so when a\r\nDataFrame was reindexed on both axes at once a column missing from the original\r\nframe was filled from whichever column sorted next to it: `bfill` and `ffill`\r\ndisagreed on the same data, and `nearest` raised `TypeError` on string labels.\r\n\r\n## Fix\r\n\r\n`method`, `limit` and `tolerance` now apply to the index only when more than one\r\naxis is reindexed. \r\n\r\nSingle-axis `df.reindex(columns=..., method=...)` is unchanged.\r\n\r\n## Checks\r\n\r\n- [x] closes pandas-dev/pandas#31002\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- (n/a) Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n- [x] I have reviewed and followed all the [contribution guidelines](https://pandas.pydata.org/docs/dev/development/contributing.html)\r\n\r\nCheck exactly one of the following, per the [automated contributions policy](https://pandas.pydata.org/docs/dev/development/contributing.html#automated-contributions-policy):\r\n\r\n- [ ] I did **not** use AI to develop this pull request.\r\n- [x] I used AI to develop this pull request. I prompted it to follow `AGENTS.md`, I have reviewed and understood every change, and I have described above how I used it and exactly which tool, model version, and effort setting — e.g. `claude opus 4.8 (xhigh)`, not just `claude`.\r\n\r\nDeveloped with Opus 5, with review by GPT 5.6 Sol and me\n',
 'closed_by': None,
 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831/reactions',
  'total_count': 0,
  '+1': 0,
  '-1': 0,
  'laugh': 0,
  'hooray': 0,
  'confused': 0,
  'heart': 0,
  'rocket': 0,
  'eyes': 0},
 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/66831/timeline',
 'performed_via_github_app': None,
 'state_reason': None}

Each element in is a dictionary containing all of the data found on a GitHub
data
issue page (except for the comments). We can pass
directly to
data
pandas.DataFrame
and extract fields of interest:

In [145]:
issues = pd.DataFrame(data, columns=["number", "title", "state", "comments", "user", "created_at"])

issues

,number,title,state,comments,user,created_at
0,66831,BUG: reindex applying method to the columns axis,open,0,"{'login': 'sanderland', 'id': 48946947, 'node_...",2026-08-18T12:24:04Z
1,66830,BUG: int64 ndarray input to PeriodArray read a...,open,0,"{'login': 'jbrockmendel', 'id': 8078968, 'node...",2026-08-18T03:13:48Z
2,66829,BUG: Period silently returned the 1970 epoch o...,open,0,"{'login': 'jbrockmendel', 'id': 8078968, 'node...",2026-08-18T03:13:16Z
3,66828,BUG: TypeError in tz_convert/tz_localize with ...,open,1,"{'login': 'jbrockmendel', 'id': 8078968, 'node...",2026-08-18T02:50:40Z
4,66827,"BUG: string ""GMT"" timezone parsed depending on...",open,0,"{'login': 'jbrockmendel', 'id': 8078968, 'node...",2026-08-18T02:43:17Z
...,...,...,...,...,...,...
25,66772,fix: ignore MultiIndex level frequency check i...,open,1,"{'login': 'SparshGarg999', 'id': 76697238, 'no...",2026-08-15T03:10:53Z
26,66769,PERF: draw wide line plots as a single collect...,open,0,"{'login': 'jbrockmendel', 'id': 8078968, 'node...",2026-08-14T19:29:32Z
27,66768,Timezone-aware Timestamp,open,3,"{'login': 's2t2', 'id': 1328807, 'node_id': 'M...",2026-08-14T19:14:21Z
28,66765,BUG: assert_frame_equal raised for freq mismat...,open,0,"{'login': 'jbrockmendel', 'id': 8078968, 'node...",2026-08-14T17:08:35Z
29,66763,TST: fix MultiIndex freq check in assert_frame...,open,1,"{'login': 'ManasDasri', 'id': 89333223, 'node_...",2026-08-14T16:45:00Z

#### Interacting with Databases

pandas has some functions to simplify loading the results of a SQL query into a
DataFrame

In [146]:
import sqlite3

query = """
    CREATE TABLE test
    (a VARCHAR(20), b VARCHAR(20),
    c REAL, d INTEGER);
"""

conn = sqlite3.connect("examples/mydata.db")

conn.execute(query)
conn.commit()

In [148]:
data = [("Atlanta", "GA", 1.245, 6),
("Macon", "GA", 2.62, 3),
("Sandy Springs", "GA", 2.71, 2),
("Savannah", "GA", 1.464, 4)]


stmt = "INSERT INTO test VALUES (?, ?, ?, ?)"

conn.executemany(stmt, data)
conn.commit()


pd.read_sql("SELECT * FROM test", conn)

               a   b      c  d
0        Atlanta  GA  1.245  6
1          Macon  GA  2.620  3
2  Sandy Springs  GA  2.710  2
3       Savannah  GA  1.464  4
4        Atlanta  GA  1.245  6
5          Macon  GA  2.620  3
6  Sandy Springs  GA  2.710  2
7       Savannah  GA  1.464  4